stages:
  - genyml
  - trigger
  - pull-n-build

# this generates our yml so we don't run on more servers than needed
generate-yml:
  stage: genyml
  script: ./scripts/_0-genyml.sh | tee cfg.yml
  artifacts:
    paths:
      - cfg.yml

trigger-ci:
  stage: trigger
  trigger:
    include:
      - artifact: cfg.yml
        job: generate-yml

