stages:
  - github
  - compile_plugins
  - genyml
  - trigger
  - fastdl

#  - test

github:
  stage: github
  script: ./scripts/push-to-github.sh
  needs: []
  tags:
  - backend
  only:
  - master
  #variables:
  #  GIT_STRATEGY: none

compile_plugins:
  stage: compile_plugins
  script: ./scripts/2-build.sh
  needs: []
  tags:
  - worker

# Secret Detection
#include:
#  - template: Secret-Detection.gitlab-ci.yml

#secret_detection:
#  tags:
#    - sast-runner


compile_plugins:
  stage: compile_plugins
  script: ./scripts/2-build.sh
  needs: []
  tags:
  - worker

# this generates our yml so we don't run on more servers than needed
generate-yml:
  stage: genyml
  script: ./scripts/0-genyml.sh | tee cfg.yml
  artifacts:
    paths:
      - cfg.yml
  tags:
    - worker
  needs: [compile_plugins]
  only:
  - master
  - staging
  - mvm
  - server/weapon-testing-event

trigger-ci:
  stage: trigger
  trigger:
    include:
      - artifact: cfg.yml
        job: generate-yml
  needs: [generate-yml]
  only:
  - master
  - staging
  - mvm
  - server/weapon-testing-event

fastdl:
  stage: fastdl
  script: ./scripts/0-fastdl.sh
  needs: [trigger-ci]
  tags:
  - fastdl
  only:
  - master
  - staging
  - mvm

