stages:
    - deploy

.deploy_template: &deploy_template
    stage: deploy
    script:
    - whoami

    - cd /srv/daemon-data
    - >
        for d in ./*/ ; do
            cd "$d";
            if [ -d ".git" ]; then

                CI_LOCAL_REMOTE=`git remote get-url origin`;
                CI_LOCAL_REMOTE="${CI_LOCAL_REMOTE##*@}";
                CI_LOCAL_REMOTE=`echo $CI_LOCAL_REMOTE | tr : /`

                CI_REMOTE_REMOTE="$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
                CI_REMOTE_REMOTE=`echo $CI_REMOTE_REMOTE | tr : /`

                if [ "$CI_LOCAL_REMOTE" == "$CI_REMOTE_REMOTE" ]; then
                    if [ `git rev-parse --abbrev-ref HEAD` == "$CI_COMMIT_REF_NAME" ]; then

                        COMMIT_OLD=`git rev-parse HEAD`;
                        echo "stashing";
                        git stash;
                        echo "fetching";
                        git fetch origin $CI_COMMIT_REF_NAME;
                        echo "resetting;
                        git reset --hard origin/$CI_COMMIT_REF_NAME;
                        echo "chmodding";
                        chmod 744 build.sh;
                        chmod 744 start.sh;
                        ./build.sh $COMMIT_OLD;
                    fi;
                fi;
            fi;
            cd ../;
        done

deploy-virginia:
    tags:
    - virginiapub
    <<: *deploy_template



