stages:
    - deploy

.deploy_template: &deploy_template
    stage: deploy
    script:
    - whoami
    - git config --global core.filemode false
    - git config --global user.email "support@creators.tf"
    - git config --global user.name "Creators.TF Production"

    - cd /srv/daemon-data
    - >
        for d in ./*/ ; do
            cd "$d";
            pwd;
            git stash;
            git fetch origin master;
            git reset --hard origin/master;

            chmod 744 build.sh;
            chmod 744 start.sh;
            ./build.sh;

            cd ../;
        done

deploy-europe:
    tags:
    - europe_public
    <<: *deploy_template

deploy-oregon:
    tags:
    - oregon_public
    <<: *deploy_template

deploy-virginia:
    tags:
    - virginia_public
    <<: *deploy_template

deploy-russia:
    tags:
    - russia_public
    <<: *deploy_template

