stages:
    - deploy

.deploy_template: &deploy_template
    stage: deploy
    script:
    - whoami

    - cd /srv/daemon-data
    - >
        for d in ./*/ ; do

            echo "Checking: $d"
            if [ -d ".git" ]; then

                CI_LOCAL_REMOTE=`git remote get-url origin`;
                CI_LOCAL_REMOTE="${CI_LOCAL_REMOTE##*@}";
                CI_LOCAL_REMOTE=`echo $CI_LOCAL_REMOTE | tr : /`

                CI_REMOTE_REMOTE="$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
                CI_REMOTE_REMOTE=`echo $CI_REMOTE_REMOTE | tr : /`

                echo "Comparing remotes $CI_LOCAL_REMOTE and $CI_REMOTE_REMOTE."
                if [ $CI_LOCAL_REMOTE != $CI_REMOTE_REMOTE ]; then continue; fi;

                echo "Comparing branches `git rev-parse --abbrev-ref HEAD` and $CI_COMMIT_REF_NAME."
                if [ `git rev-parse --abbrev-ref HEAD` != $CI_COMMIT_REF_NAME ]; then continue; fi;

                git config --global user.email "support@creators.tf"
                git config --global user.name "Creators.TF Production"

                COMMIT_OLD=`git rev-parse HEAD`;
                git stash;

                git fetch origin $CI_COMMIT_REF_NAME;
                git reset --hard origin/$CI_COMMIT_REF_NAME;

                chmod 744 build.sh;
                chmod 744 start.sh;
                ./build.sh $COMMIT_OLD;

            fi;
            cd ../;
        done

deploy-europe:
    tags:
    - eupub
    <<: *deploy_template

deploy-oregon:
    tags:
    - oregonpub
    <<: *deploy_template

deploy-virginia:
    tags:
    - virginiapub
    <<: *deploy_template

deploy-russia:
    tags:
    - russiapub
    <<: *deploy_template
