stages:
    - deploy

.deploy_template: &deploy_template
    stage: deploy
    script:
    - chmod +x ./scripts/ci.sh
    # read the script if you're gonna mess with flags PLEASE
    - bash ./scripts/ci.sh

deploy-europe:
    tags:
    - eupub
    <<: *deploy_template

deploy-europe2:
    tags:
    - eu2pub
    <<: *deploy_template

deploy-virginia:
    tags:
    - virginiapub
    <<: *deploy_template

deploy-singapore:
    tags:
    - sgppub
    <<: *deploy_template

deploy-australia:
    tags:
    - auspub
    <<: *deploy_template

deploy-la:
    tags:
    - lapub
    <<: *deploy_template

deploy-chicago3:
    tags:
    - chicago3
    <<: *deploy_template

#deploy-uspotato1:
#    tags:
#    - uspotato1
#    <<: *deploy_template

deploy-eupotato1:
    tags:
    - eupotato1
    <<: *deploy_template

#deploy-eupotato2:
#    tags:
#    - eupotato2
#    <<: *deploy_template

# TODO: why is this here? doesn't this run on the backend server? dafaq?
deploy-fastdl:
    stage: deploy
    script:
    - whoami
    - shopt -s globstar

    - SHA_BEFORE="$CI_COMMIT_BEFORE_SHA"
    - SHA_AFTER="$CI_COMMIT_SHA"

    - echo "Comparing $SHA_BEFORE // $SHA_AFTER"
    - GIT_DIFF=`git diff --name-only $SHA_AFTER $SHA_BEFORE`

    - cd $CI_PROJECT_DIR
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME

    - echo "[INFO] Repository path = $CI_PROJECT_DIR"

    - FASTDL_PATH="/var/www/fastdl/content/branches/$CI_COMMIT_REF_NAME";
    - cd tf;

    - >
        while read pattern; do

            echo "Pattern: $pattern"

            # We go through all the files of this pattern and see if bz2 version is valid.
            for i in ./$pattern; do

                # Skip missing files.
                [[ ! -f $i ]] && continue;

                ASSET_SRC_PATH=`realpath $i`;
                ASSET_FASTDL_PATH=$FASTDL_PATH/$i;
                ASSET_BZ2_PATH=$ASSET_FASTDL_PATH.bz2;

                RECOMPRESS=0;

                # Recompress if bz2 file does not exist.
                [[ ! -f $ASSET_BZ2_PATH ]] && RECOMPRESS=1;

                # Recomress if checksums do not match.
                if [[ $RECOMPRESS = 0 ]]; then

                    GIT_DIFF_ELEMENT=`realpath --relative-to ./ $i`;

                    # If it exist, let's first check if it changed.
                    if [[ `echo $GIT_DIFF | grep $GIT_DIFF_ELEMENT` ]]; then
                        RECOMPRESS=1;
                    fi
                fi

                if [[ $RECOMPRESS = 1 ]]; then

                    # Remove old bz2 if exists.
                    [[ -f $ASSET_BZ2_PATH ]] && rm $ASSET_BZ2_PATH;

                    # Validate directories
                    mkdir -p ${ASSET_FASTDL_PATH%/*}

                    # Copying the src file.
                    cp $ASSET_SRC_PATH $ASSET_FASTDL_PATH;

                    echo "[INFO] Archiving $ASSET_FASTDL_PATH";
                    bzip2 $ASSET_FASTDL_PATH;
                fi

            done
        done < ../.ci-fastdl
    - exit

    tags:
    - fastdl
    only:
    - master
    - staging
    - mvm
    
