stages:
    - deploy

.deploy_template: &deploy_template
    stage: deploy
    script:
    - whoami
    - git config --global core.filemode false
    - git config --global user.email "support@creators.tf"
    - git config --global user.name "Creators.TF Production"
    - bash do.sh


deploy-europe:
    tags:
    - europe_public
    <<: *deploy_template

deploy-oregon:
    tags:
    - oregon_public
    <<: *deploy_template

deploy-virginia:
    tags:
    - virginia_public
    <<: *deploy_template

deploy-russia:
    tags:
    - russia_public
    <<: *deploy_template


