stages:
    - deploy

.deploy_template: &deploy_template
    stage: deploy
    script:
    - whoami
    - git config --global core.filemode false
    - git config --global user.email "support@creators.tf"
    - git config --global user.name "Creators.TF Production"

    - cd /srv/daemon-data
    - >
        for d in ./*/ ; do
            cd "$d";
            pwd;
            echo "stashing git"
            git stash;
            echo "fetching git"
            git fetch origin master;
            echo "resetting git"
            git reset --hard origin/master;
            echo "pulling git"
            git pull
            echo "chmodding"
            chmod 744 build.sh;
            chmod 744 start.sh;
            echo "starting compile script"
            bash ./build.sh;
            echo "leaving directory"
            cd ../;
        done

deploy-europe:
    tags:
    - europe_public
    <<: *deploy_template

deploy-oregon:
    tags:
    - oregon_public
    <<: *deploy_template

deploy-virginia:
    tags:
    - virginia_public
    <<: *deploy_template

deploy-russia:
    tags:
    - russia_public
    <<: *deploy_template

